name: PurgeCSS Automation

on:
  push:
    branches: [main]

jobs:
  purge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install PostCSS and PurgeCSS
        run: |
          npm install postcss postcss-cli @fullhuman/postcss-purgecss

      - name: Write postcss.config.js (CommonJS mode)
        run: |
          echo "module.exports = {\n  plugins: [\n    require('@fullhuman/postcss-purgecss')({\n      content: ['./index.html'],\n      defaultExtractor: content => content.match(/[\w-/:]+(?<!:)/g) || []\n    })\n  ]\n};" > postcss.config.js

      - name: Run PostCSS (PurgeCSS)
        run: npx postcss input.css -o purged.css

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
