name: PurgeCSS Automation

on:
  push:
    branches: [main]

jobs:
  purge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install postcss postcss-cli @fullhuman/postcss-purgecss

      - name: Create postcss.config.js
        run: |
          echo "module.exports = {
            plugins: [
              require('@fullhuman/postcss-purgecss')({
                content: ['./index.html'],
                defaultExtractor: content => content.match(/[\w-/:]+(?<!:)/g) || []
              })
            ]
          };" > postcss.config.js

      - name: Run PurgeCSS
        run: |
          npx postcss input.css -o purged.css

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
