name: PurgeCSS Automation

on:
  push:
    branches: [main]

jobs:
  purge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install PostCSS and PurgeCSS
        run: |
          npm install postcss postcss-cli @fullhuman/postcss-purgecss

      - name: Create postcss.config.js in CommonJS
        run: |
          echo "module.exports = {" > postcss.config.js
          echo "  plugins: [" >> postcss.config.js
          echo "    require('@fullhuman/postcss-purgecss')({" >> postcss.config.js
          echo "      content: ['./index.html']," >> postcss.config.js
          echo "      defaultExtractor: content => content.match(/[\\w-/:]+(?<!:)/g) || []" >> postcss.config.js
          echo "    })" >> postcss.config.js
          echo "  ]" >> postcss.config.js
          echo "};" >> postcss.config.js

      - name: Run PostCSS (PurgeCSS)
        run: npx postcss input.css -o purged.css

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
